-- 댓글 테이블에 deleted 컬럼과 updated_at 컬럼 추가
ALTER TABLE comments ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE comments ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
